// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace mu_marketplaceV0.Migrations
{
    [DbContext(typeof(SongMetaDbContext))]
    [Migration("20250517043819_PendingChangesFix")]
    partial class PendingChangesFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("mu_marketplaceV0.Models.SongNFTMetadata", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("artist");

                    b.Property<int>("AscapShare")
                        .HasColumnType("int")
                        .HasColumnName("ascap_share");

                    b.Property<string>("Copyright")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("copyright");

                    b.Property<string>("Distributor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("distributor");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("int")
                        .HasColumnName("duration_seconds");

                    b.Property<bool>("Explicit")
                        .HasColumnType("bit")
                        .HasColumnName("explicit");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image_url");

                    b.Property<string>("Isrc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("isrc");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("language");

                    b.Property<string>("OriginCountry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("origin_country");

                    b.Property<string>("Publisher1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("publisher_1");

                    b.Property<string>("Publisher2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("publisher_2");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("release_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("title");

                    b.Property<string>("Writer1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("writer_1");

                    b.Property<string>("Writer2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("writer_2");

                    b.HasKey("Id");

                    b.ToTable("SongNFTMetadata");
                });
#pragma warning restore 612, 618
        }
    }
}
